# Traefik Dynamic Configuration
# ==============================

tls:
  certificates:
    - certFile: /certs/origin.crt
      keyFile: /certs/origin.key

  stores:
    default:
      defaultCertificate:
        certFile: /certs/origin.crt
        keyFile: /certs/origin.key
